name: 每日18点推送合肥美食
on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  run_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 设置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: 安装依赖
        run: pip install requests
      - name: 执行推送
        run: python send_wxpush.py
